//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmrittulyaTeaShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeaShop
    {
        public int ComponentId { get; set; }
        public string ComponentName { get; set; }
        public string Description { get; set; }
        public Nullable<double> Price { get; set; }
        public string Picture { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string AlternateText { get; set; }

    }
}
